name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8
        run: flake8 .

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -f succession_insights/Dockerfile -t stevems/succession_moods:latest .

      - name: Capture Docker build logs
        run: |
          docker build -f succession_insights/Dockerfile -t stevems/succession_moods:latest . || (echo "Docker build failed" && exit 1)

      - name: Push Docker image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u stevems --password-stdin
          docker push stevems/succession_moods:latest


      - name: Deploy to Render
        run: |
          curl -v -X POST ${{ secrets.RENDER_SERVICE_ID }} \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
